// Declare the llvmpy entry function generated by the compiler.
// It should return an int (the exit code).
#include "Debugdefine.h"

extern int __llvmpy_entry();

#ifdef RUNTIME_TIMER
#include <stdio.h>
#include <time.h>
#endif

// Standard C main function.
int main(int argc, char **argv) {
#ifdef RUNTIME_TIMER
    struct timespec start, end;
    double time_spent;

    // Record start time
    clock_gettime(CLOCK_MONOTONIC, &start);
#endif

    // Call the function generated by the llvmpy compiler.
    int exit_code = __llvmpy_entry();

#ifdef RUNTIME_TIMER
    // Record end time
    clock_gettime(CLOCK_MONOTONIC, &end);

    // Calculate the time spent in seconds
    time_spent = (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1000000000.0;

    // Print the execution time to stdout
    printf("Execution time: %f seconds\n", time_spent);
#endif

    return exit_code;
}