// Declare the llvmpy entry function generated by the compiler.
// It should return an int (the exit code).
extern int __llvmpy_entry();

// Standard C main function.
int main(int argc, char **argv) {
    // Call the function generated by the llvmpy compiler.
    int exit_code = __llvmpy_entry();
    return exit_code;
}